{% set name = "mffpy" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: daaf3d018e7bb4a6827e4bb32d7877a3cc78e1bc97c2b0f3d1027e7ae1724eef

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.15.1
    - pytz >=2019.2
    - deprecated >=1.2.12
    - lxml >=4.8.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - mffpy
    - mffpy.writer

about:
  home: https://github.com/BEL-Public/mffpy
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A lean reader for EGI's MFF file format.

extra:
  recipe-maintainers:
    - mscheltienne
    - larsoner
    - hoechenberger
