{% set name = "mffpy" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: aa5daab70109bb466a352156386a2072693994b7d0d5b24ac0df9cb9e0ca92ed

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.15.1
    - pytz >=2019.2
    - deprecated >=1.2.12
    - lxml >=4.8.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - mffpy
    - mffpy.writer

about:
  home: https://github.com/BEL-Public/mffpy
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A lean reader for EGI's MFF file format.

extra:
  recipe-maintainers:
    - mscheltienne
    - larsoner
    - hoechenberger
